site_name: K-Notes
nav:
  - トップ: index.md
  # - index.md
  - PyGMT: 
    - pygmt/index.md
    - pygmt/sec001.md
    - pygmt/sec002.md
    - pygmt/sec003.md
    - pygmt/sec004.md
    - pygmt/sec005.md
    - pygmt/sec006.md
    - pygmt/sec007.md
    - pygmt/sec008.md
    - pygmt/sec009.md
    - pygmt/sec010.md
    - pygmt/sec011.md
    - pygmt/sec012.md
    - pygmt/sec013.md
    - pygmt/sec014.md
    - pygmt/sec015.md

  - Matplotlib:
    # - matplotlib/index.md
    - plt/sec001.md
  - Ubuntu:
    # - ubuntu/index.md
    - ubuntu/sec001.md
  - WINシステム:
    # - win/index.md
    - win/sec001.md
  - about.md

site_url: https://is-enaga.github.io/k-notes
repo_url: https://github.com/is-enaga/k-notes

theme:
  name: material
  palette:
    - scheme: default
      primary: "red"
      accent: "indigo"
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: "pink"
      accent: "light blue"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  
  font:
    text: Noto Sans JP
    code: cascadia code
  language: ja
  
  logo: assets/logo.jpg
  favicon: assets/logo.jpg

  features:
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    # - navigation.expand
    - navigation.indexes
    - toc.follow
    # - toc.integrate
    - navigation.top

    - search.suggest
    - search.highlight
    - search.share

    - header.autohide

    - navigation.footer

    - content.code.copy # コードのコピーボタン https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=code

extra:
  # homepage: https://is-enaga.github.io/k-notes
  
  search:
      language: 'jp'

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/is-enaga
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/winter2enaga

  consent:
    actions:
      - accept
      - manage
    title: Cookie consent
    description: >- 
      本サイトでは，サイトの構成の改善のためにGoogleによるアクセス解析ツール「Googleアナリティクス」を使用しています．
      このGoogleアナリティクスはCookieを使用します。このデータは匿名で収集されており、個人を特定することはできません。
      また広告等の収益目的にも使用しておりません．

      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: true

  analytics:
    provider: google
    property: G-SR97P4JMJ9
    feedback:
      title:  ---
      ratings:
        - icon: material/heart
          name: いいね!
          data: 1
          note: >-
            ご協力ありがとうございます! ご希望，ご指摘等があれば，GitHubのissuesでお気軽にお伝えください． <a href="https://github.com/is-enaga/k-notes/issues" target="_blank" rel="noopener">issues</a>
        - icon: material/heart-broken
          name: がんばって!
          data: 0
          note: >- 
            ご協力ありがとうございます! ご希望，ご指摘等があれば，GitHubのissuesでお気軽にお伝えください． <a href="https://github.com/is-enaga/k-notes/issues" target="_blank" rel="noopener">issues</a>
copyright: >
  Copyright &copy; 2024 Kei Shiraiwa –
  <a href="#__consent">Cookieの設定</a>

plugins:
  - privacy
  - search

extra_javascript: 
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
  - js/config.js

extra_css:
    - stylesheets/extra.css
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      line_spans: __span
      pygments_lang_class: true
      noclasses: true
      pygments_style: monokai
      # linenums: true # 番号の位置がずれるので没
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  # - pymdownx.snippets

